; ESP32 DIY V1 pinout adapted for Elecrow LR1262 (SX1262)
[env:meshtastic-diy-lr1262]
custom_meshtastic_hw_model = 39
custom_meshtastic_hw_model_slug = DIY_V1
custom_meshtastic_architecture = esp32
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = DIY V1 + LR1262
custom_meshtastic_images = diy.svg
custom_meshtastic_tags = DIY
extends = esp32_base
board_level = release
board = esp32doit-devkit-v1
build_flags =
  ${esp32_base.build_flags}
  -D DIY_V1
  -D DIY_LR1262
  -I variants/esp32/diy/lr1262
